{
 "title": "Docker_Swarm",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(container_label_com_docker_swarm_node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "count node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(container_label_com_docker_swarm_node_id) (container_last_seen{container_label_com_docker_swarm_node_id=~\"$Node\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_com_docker_swarm_task_id!=\"\", container_label_com_docker_swarm_node_id=~\"$Node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count stack",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace!=\"\"}) by (container_label_com_docker_stack_namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by services",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg by(container_label_com_docker_swarm_service_name) (irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name!=\"\", container_label_com_docker_stack_namespace=\"stage\", container_label_com_docker_swarm_node_id=~\"$Node\"}[1m]))*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}