{
 "title": "Application is a room booking service",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values({job=~\"report-service|booking-service|gateway-service|session-service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "количество обработанных сообщений в rabbitmq",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (http_server_requests_seconds_count{job=~\"booking-service|report-service\", status=~\"200|201\", instance=~\"$Node\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "количество отправленных сообщений в rabbitmq",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (http_server_requests_seconds_count{job=~\"booking-service|report-service\", instance=~\"$Node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "количество бронирований",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"booking-service\", status=~\"200|201\", instance=~\"$Node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "количество полученных запросов на gateway",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=~\".*gateway.*\", instance=~\"$Node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "количество полученных запросов на авторизацию пользователей",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"session-service\", uri=\"/api/v1/auth/authorize\", instance=~\"$Node\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}