global:
  scrape_interval: 20s

scrape_configs:
  - job_name: node
    dns_sd_configs:
      - names: 
          - tasks.node_exporter
        type: A  
        port: 9100

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    dns_sd_configs:
      - names: 
          - tasks.blackbox
        type: A
        port: 9115
    relabel_configs:
      - source_labels: []
        target_label: __param_target
        replacement: google.com


  - job_name: cadvisor
    scrape_interval: 5s
    dns_sd_configs:
      - names: 
          - tasks.cadvisor
        type: A
        port: 8080

  - job_name: session-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: 
          - tasks.session
        type: A
        port: 8081

  - job_name: booking-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: 
          - tasks.booking
        type: A
        port: 8083

  - job_name: report-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: 
          - tasks.report
        type: A
        port: 8086

  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: 
          - tasks.gateway
        type: A
        port: 8087
  
rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"